export const data: any = [
  [
    {
      id: "1a",
      model: "HD1500",
      equipmentName: "DT101",
      loadsCompleted: "9/35",
      trips: "Trip1",
      materialType: "Waste",
      actual: "10",
      planned: "10",
      tonnesIndicated: "10",
      avgLoadCarriedBack: "10",
      actualTonnes: "10",
    },
    {
      id: "1a",
      model: "HD1500",
      equipmentName: "DT101",
      loadsCompleted: "9/35",
      trips: "Trip1",
      materialType: "Waste",
      actual: "10",
      planned: "10",
      tonnesIndicated: "10",
      avgLoadCarriedBack: "10",
      actualTonnes: "10",
    },
  ],
  [
    {
      id: "1a",
      model: "HD1500",
      equipmentName: "DT101",
      loadsCompleted: "9/35",
      trips: "Trip1",
      materialType: "Waste",
      actual: "20",
      planned: "20",
      tonnesIndicated: "20",
      avgLoadCarriedBack: "20",
      actualTonnes: "20",
    },
    {
      id: "1b",
      model: "HD1500",
      equipmentName: "DT101",
      loadsCompleted: "9/35",
      trips: "Trip1",
      materialType: "Waste",
      actual: "20",
      planned: "20",
      tonnesIndicated: "20",
      avgLoadCarriedBack: "20",
      actualTonnes: "20",
    },
  ],
];
