export const data: any = [
  [
    {
      id: "1a",
      model: "HD785",
      equipmentName: "DT101",
      loadsCompleted: "11",
      trips: "Trip1",
      materialType: "Waste",
      actual: "902",
      planned: "2975",
      tonnesIndicated: "10",
      avgLoadCarriedBack: "10",
      actualTonnes: "10",
    },
    {
      id: "1a",
      model: "HD785",
      equipmentName: "DT102",
      loadsCompleted: "8",
      trips: "Trip1",
      materialType: "Waste",
      actual: "663",
      planned: "2975",
      tonnesIndicated: "10",
      avgLoadCarriedBack: "10",
      actualTonnes: "10",
    },
  ],
  [
    {
      id: "1b",
      model: "HD1500",
      equipmentName: "DT121",
      loadsCompleted: "10",
      trips: "Trip1",
      materialType: "Waste",
      actual: "1452",
      planned: "5250",
      tonnesIndicated: "20",
      avgLoadCarriedBack: "20",
      actualTonnes: "20",
    },
    {
      id: "1b",
      model: "HD1500",
      equipmentName: "DT122",
      loadsCompleted: "9",
      trips: "Trip1",
      materialType: "Waste",
      actual: "1332",
      planned: "5250",
      tonnesIndicated: "20",
      avgLoadCarriedBack: "20",
      actualTonnes: "20",
    },
  ],
];
